// Code generated by the Encore 1.51.6 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly call: call.ServiceClient
    public readonly chat: chat.ServiceClient
    public readonly friend: friend.ServiceClient
    public readonly message: message.ServiceClient
    public readonly notification: notification.ServiceClient
    public readonly presence: presence.ServiceClient
    public readonly status: status.ServiceClient
    public readonly user: user.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.call = new call.ServiceClient(base)
        this.chat = new chat.ServiceClient(base)
        this.friend = new friend.ServiceClient(base)
        this.message = new message.ServiceClient(base)
        this.notification = new notification.ServiceClient(base)
        this.presence = new presence.ServiceClient(base)
        this.status = new status.ServiceClient(base)
        this.user = new user.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * Import the auth handler to be able to derive the auth type
 */
import type { auth as auth_auth } from "~backend/auth/auth";

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: RequestType<typeof auth_auth> | AuthDataGenerator
}


export namespace auth {
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { answer as api_call_answer_answer } from "~backend/call/answer";
import { end as api_call_end_end } from "~backend/call/end";
import { initiate as api_call_initiate_initiate } from "~backend/call/initiate";
import { reject as api_call_reject_reject } from "~backend/call/reject";
import { signal as api_call_signal_signal } from "~backend/call/signal";
import { stream as api_call_stream_stream } from "~backend/call/stream";

export namespace call {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.answer = this.answer.bind(this)
            this.end = this.end.bind(this)
            this.initiate = this.initiate.bind(this)
            this.reject = this.reject.bind(this)
            this.signal = this.signal.bind(this)
            this.stream = this.stream.bind(this)
        }

        public async answer(params: { callId: string }): Promise<ResponseType<typeof api_call_answer_answer>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calls/${encodeURIComponent(params.callId)}/answer`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_call_answer_answer>
        }

        public async end(params: { callId: string }): Promise<ResponseType<typeof api_call_end_end>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calls/${encodeURIComponent(params.callId)}/end`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_call_end_end>
        }

        public async initiate(params: RequestType<typeof api_call_initiate_initiate>): Promise<ResponseType<typeof api_call_initiate_initiate>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calls/initiate`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_call_initiate_initiate>
        }

        public async reject(params: { callId: string }): Promise<ResponseType<typeof api_call_reject_reject>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calls/${encodeURIComponent(params.callId)}/reject`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_call_reject_reject>
        }

        public async signal(params: RequestType<typeof api_call_signal_signal>): Promise<ResponseType<typeof api_call_signal_signal>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/calls/signal`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_call_signal_signal>
        }

        public async stream(): Promise<StreamIn<StreamResponse<typeof api_call_stream_stream>>> {
            return await this.baseClient.createStreamIn(`/calls/stream`)
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { addParticipant as api_chat_add_participant_addParticipant } from "~backend/chat/add_participant";
import { create as api_chat_create_create } from "~backend/chat/create";
import { createGroup as api_chat_create_group_createGroup } from "~backend/chat/create_group";
import { get as api_chat_get_get } from "~backend/chat/get";
import { getGroupMembers as api_chat_get_group_members_getGroupMembers } from "~backend/chat/get_group_members";
import { getPinnedMessages as api_chat_get_pinned_getPinnedMessages } from "~backend/chat/get_pinned";
import { list as api_chat_list_list } from "~backend/chat/list";
import { muteChat as api_chat_mute_muteChat } from "~backend/chat/mute";
import { pinMessage as api_chat_pin_message_pinMessage } from "~backend/chat/pin_message";
import { removeParticipant as api_chat_remove_participant_removeParticipant } from "~backend/chat/remove_participant";
import { setAdmin as api_chat_set_admin_setAdmin } from "~backend/chat/set_admin";
import { unpinMessage as api_chat_unpin_message_unpinMessage } from "~backend/chat/unpin_message";
import { updateGroup as api_chat_update_group_updateGroup } from "~backend/chat/update_group";
import { updateGroupSettings as api_chat_update_group_settings_updateGroupSettings } from "~backend/chat/update_group_settings";
import { updateMemberRole as api_chat_update_member_role_updateMemberRole } from "~backend/chat/update_member_role";

export namespace chat {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.addParticipant = this.addParticipant.bind(this)
            this.create = this.create.bind(this)
            this.createGroup = this.createGroup.bind(this)
            this.get = this.get.bind(this)
            this.getGroupMembers = this.getGroupMembers.bind(this)
            this.getPinnedMessages = this.getPinnedMessages.bind(this)
            this.list = this.list.bind(this)
            this.muteChat = this.muteChat.bind(this)
            this.pinMessage = this.pinMessage.bind(this)
            this.removeParticipant = this.removeParticipant.bind(this)
            this.setAdmin = this.setAdmin.bind(this)
            this.unpinMessage = this.unpinMessage.bind(this)
            this.updateGroup = this.updateGroup.bind(this)
            this.updateGroupSettings = this.updateGroupSettings.bind(this)
            this.updateMemberRole = this.updateMemberRole.bind(this)
        }

        public async addParticipant(params: RequestType<typeof api_chat_add_participant_addParticipant>): Promise<ResponseType<typeof api_chat_add_participant_addParticipant>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                isAdmin: params.isAdmin,
                userId:  params.userId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/${encodeURIComponent(params.chatId)}/participants`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_add_participant_addParticipant>
        }

        public async create(params: RequestType<typeof api_chat_create_create>): Promise<ResponseType<typeof api_chat_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_create_create>
        }

        public async createGroup(params: RequestType<typeof api_chat_create_group_createGroup>): Promise<ResponseType<typeof api_chat_create_group_createGroup>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/group`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_create_group_createGroup>
        }

        public async get(params: { chatId: string }): Promise<ResponseType<typeof api_chat_get_get>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/${encodeURIComponent(params.chatId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_get_get>
        }

        public async getGroupMembers(params: { chatId: string }): Promise<ResponseType<typeof api_chat_get_group_members_getGroupMembers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/group/${encodeURIComponent(params.chatId)}/members`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_get_group_members_getGroupMembers>
        }

        public async getPinnedMessages(params: { chatId: string }): Promise<ResponseType<typeof api_chat_get_pinned_getPinnedMessages>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/${encodeURIComponent(params.chatId)}/pinned`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_get_pinned_getPinnedMessages>
        }

        public async list(params: RequestType<typeof api_chat_list_list>): Promise<ResponseType<typeof api_chat_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                search: params.search,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_list_list>
        }

        public async muteChat(params: RequestType<typeof api_chat_mute_muteChat>): Promise<ResponseType<typeof api_chat_mute_muteChat>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                isMuted:   params.isMuted,
                muteUntil: params.muteUntil,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/${encodeURIComponent(params.chatId)}/mute`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_mute_muteChat>
        }

        public async pinMessage(params: { chatId: string, messageId: string }): Promise<ResponseType<typeof api_chat_pin_message_pinMessage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/${encodeURIComponent(params.chatId)}/pin/${encodeURIComponent(params.messageId)}`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_pin_message_pinMessage>
        }

        public async removeParticipant(params: { chatId: string, userId: string }): Promise<ResponseType<typeof api_chat_remove_participant_removeParticipant>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/${encodeURIComponent(params.chatId)}/participants/${encodeURIComponent(params.userId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_remove_participant_removeParticipant>
        }

        public async setAdmin(params: RequestType<typeof api_chat_set_admin_setAdmin>): Promise<ResponseType<typeof api_chat_set_admin_setAdmin>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                isAdmin: params.isAdmin,
                userId:  params.userId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/${encodeURIComponent(params.chatId)}/admin`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_set_admin_setAdmin>
        }

        public async unpinMessage(params: { chatId: string, messageId: string }): Promise<ResponseType<typeof api_chat_unpin_message_unpinMessage>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/${encodeURIComponent(params.chatId)}/pin/${encodeURIComponent(params.messageId)}`, {method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_unpin_message_unpinMessage>
        }

        public async updateGroup(params: RequestType<typeof api_chat_update_group_updateGroup>): Promise<ResponseType<typeof api_chat_update_group_updateGroup>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description:   params.description,
                groupImageUrl: params.groupImageUrl,
                name:          params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/${encodeURIComponent(params.chatId)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_update_group_updateGroup>
        }

        public async updateGroupSettings(params: RequestType<typeof api_chat_update_group_settings_updateGroupSettings>): Promise<ResponseType<typeof api_chat_update_group_settings_updateGroupSettings>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                description:   params.description,
                groupImageUrl: params.groupImageUrl,
                name:          params.name,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/group/${encodeURIComponent(params.chatId)}/settings`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_update_group_settings_updateGroupSettings>
        }

        public async updateMemberRole(params: RequestType<typeof api_chat_update_member_role_updateMemberRole>): Promise<ResponseType<typeof api_chat_update_member_role_updateMemberRole>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                isAdmin: params.isAdmin,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/chats/group/${encodeURIComponent(params.chatId)}/members/${encodeURIComponent(params.userId)}/role`, {method: "PATCH", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_chat_update_member_role_updateMemberRole>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { acceptRequest as api_friend_accept_request_acceptRequest } from "~backend/friend/accept_request";
import { listFriends as api_friend_list_friends_listFriends } from "~backend/friend/list_friends";
import { listRequests as api_friend_list_requests_listRequests } from "~backend/friend/list_requests";
import { rejectRequest as api_friend_reject_request_rejectRequest } from "~backend/friend/reject_request";
import { sendRequest as api_friend_send_request_sendRequest } from "~backend/friend/send_request";

export namespace friend {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.acceptRequest = this.acceptRequest.bind(this)
            this.listFriends = this.listFriends.bind(this)
            this.listRequests = this.listRequests.bind(this)
            this.rejectRequest = this.rejectRequest.bind(this)
            this.sendRequest = this.sendRequest.bind(this)
        }

        public async acceptRequest(params: { requestId: string }): Promise<ResponseType<typeof api_friend_accept_request_acceptRequest>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/friend/requests/${encodeURIComponent(params.requestId)}/accept`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_friend_accept_request_acceptRequest>
        }

        public async listFriends(): Promise<ResponseType<typeof api_friend_list_friends_listFriends>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/friends`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_friend_list_friends_listFriends>
        }

        public async listRequests(): Promise<ResponseType<typeof api_friend_list_requests_listRequests>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/friend/requests`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_friend_list_requests_listRequests>
        }

        public async rejectRequest(params: { requestId: string }): Promise<ResponseType<typeof api_friend_reject_request_rejectRequest>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/friend/requests/${encodeURIComponent(params.requestId)}/reject`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_friend_reject_request_rejectRequest>
        }

        public async sendRequest(params: RequestType<typeof api_friend_send_request_sendRequest>): Promise<ResponseType<typeof api_friend_send_request_sendRequest>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/friend/requests`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_friend_send_request_sendRequest>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { deleteMessage as api_message_delete_deleteMessage } from "~backend/message/delete";
import { edit as api_message_edit_edit } from "~backend/message/edit";
import { getStats as api_message_get_stats_getStats } from "~backend/message/get_stats";
import { list as api_message_list_list } from "~backend/message/list";
import { markRead as api_message_mark_read_markRead } from "~backend/message/mark_read";
import { send as api_message_send_send } from "~backend/message/send";
import { stream as api_message_stream_stream } from "~backend/message/stream";
import { uploadAttachment as api_message_upload_attachment_uploadAttachment } from "~backend/message/upload_attachment";

export namespace message {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.deleteMessage = this.deleteMessage.bind(this)
            this.edit = this.edit.bind(this)
            this.getStats = this.getStats.bind(this)
            this.list = this.list.bind(this)
            this.markRead = this.markRead.bind(this)
            this.send = this.send.bind(this)
            this.stream = this.stream.bind(this)
            this.uploadAttachment = this.uploadAttachment.bind(this)
        }

        public async deleteMessage(params: RequestType<typeof api_message_delete_deleteMessage>): Promise<ResponseType<typeof api_message_delete_deleteMessage>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                deleteForEveryone: String(params.deleteForEveryone),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/messages/${encodeURIComponent(params.messageId)}`, {query, method: "DELETE", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_message_delete_deleteMessage>
        }

        public async edit(params: RequestType<typeof api_message_edit_edit>): Promise<ResponseType<typeof api_message_edit_edit>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                content: params.content,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/messages/${encodeURIComponent(params.messageId)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_message_edit_edit>
        }

        public async getStats(params: RequestType<typeof api_message_get_stats_getStats>): Promise<ResponseType<typeof api_message_get_stats_getStats>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                userId: params.userId,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/messages/stats/${encodeURIComponent(params.chatId)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_message_get_stats_getStats>
        }

        public async list(params: RequestType<typeof api_message_list_list>): Promise<ResponseType<typeof api_message_list_list>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                before: params.before,
                limit:  params.limit === undefined ? undefined : String(params.limit),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/messages/chat/${encodeURIComponent(params.chatId)}`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_message_list_list>
        }

        public async markRead(params: RequestType<typeof api_message_mark_read_markRead>): Promise<ResponseType<typeof api_message_mark_read_markRead>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                lastMessageId: params.lastMessageId,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/messages/${encodeURIComponent(params.chatId)}/mark-read`, {method: "POST", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_message_mark_read_markRead>
        }

        public async send(params: RequestType<typeof api_message_send_send>): Promise<ResponseType<typeof api_message_send_send>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/messages`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_message_send_send>
        }

        public async stream(params: RequestType<typeof api_message_stream_stream>): Promise<StreamIn<StreamResponse<typeof api_message_stream_stream>>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                chatId: params.chatId,
            })

            return await this.baseClient.createStreamIn(`/messages/stream`, {query})
        }

        public async uploadAttachment(params: RequestType<typeof api_message_upload_attachment_uploadAttachment>): Promise<ResponseType<typeof api_message_upload_attachment_uploadAttachment>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/messages/attachment/upload-url`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_message_upload_attachment_uploadAttachment>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { list as api_notification_list_list } from "~backend/notification/list";
import { markAllRead as api_notification_mark_all_read_markAllRead } from "~backend/notification/mark_all_read";
import { markRead as api_notification_mark_read_markRead } from "~backend/notification/mark_read";
import { stream as api_notification_stream_stream } from "~backend/notification/stream";

export namespace notification {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.list = this.list.bind(this)
            this.markAllRead = this.markAllRead.bind(this)
            this.markRead = this.markRead.bind(this)
            this.stream = this.stream.bind(this)
        }

        public async list(): Promise<ResponseType<typeof api_notification_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notification_list_list>
        }

        public async markAllRead(): Promise<ResponseType<typeof api_notification_mark_all_read_markAllRead>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/read-all`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notification_mark_all_read_markAllRead>
        }

        public async markRead(params: { notificationId: string }): Promise<ResponseType<typeof api_notification_mark_read_markRead>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/notifications/${encodeURIComponent(params.notificationId)}/read`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_notification_mark_read_markRead>
        }

        public async stream(): Promise<StreamIn<StreamResponse<typeof api_notification_stream_stream>>> {
            return await this.baseClient.createStreamIn(`/notifications/stream`)
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getOnlineUsers as api_presence_get_online_users_getOnlineUsers } from "~backend/presence/get_online_users";
import { getUserStatus as api_presence_get_user_status_getUserStatus } from "~backend/presence/get_user_status";
import { stream as api_presence_stream_stream } from "~backend/presence/stream";
import { updateOnlineStatus as api_presence_update_online_status_updateOnlineStatus } from "~backend/presence/update_online_status";
import { updateTyping as api_presence_update_typing_updateTyping } from "~backend/presence/update_typing";

export namespace presence {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getOnlineUsers = this.getOnlineUsers.bind(this)
            this.getUserStatus = this.getUserStatus.bind(this)
            this.stream = this.stream.bind(this)
            this.updateOnlineStatus = this.updateOnlineStatus.bind(this)
            this.updateTyping = this.updateTyping.bind(this)
        }

        public async getOnlineUsers(params: { chatId: string }): Promise<ResponseType<typeof api_presence_get_online_users_getOnlineUsers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/presence/online/${encodeURIComponent(params.chatId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_presence_get_online_users_getOnlineUsers>
        }

        public async getUserStatus(params: { userId: string }): Promise<ResponseType<typeof api_presence_get_user_status_getUserStatus>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/presence/status/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_presence_get_user_status_getUserStatus>
        }

        public async stream(params: RequestType<typeof api_presence_stream_stream>): Promise<StreamIn<StreamResponse<typeof api_presence_stream_stream>>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                chatId: params.chatId,
            })

            return await this.baseClient.createStreamIn(`/presence/stream`, {query})
        }

        public async updateOnlineStatus(params: RequestType<typeof api_presence_update_online_status_updateOnlineStatus>): Promise<ResponseType<typeof api_presence_update_online_status_updateOnlineStatus>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/presence/online`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_presence_update_online_status_updateOnlineStatus>
        }

        public async updateTyping(params: RequestType<typeof api_presence_update_typing_updateTyping>): Promise<ResponseType<typeof api_presence_update_typing_updateTyping>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/presence/typing`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_presence_update_typing_updateTyping>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { create as api_status_create_create } from "~backend/status/create";
import { getViewers as api_status_get_viewers_getViewers } from "~backend/status/get_viewers";
import { list as api_status_list_list } from "~backend/status/list";
import { view as api_status_view_view } from "~backend/status/view";

export namespace status {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.create = this.create.bind(this)
            this.getViewers = this.getViewers.bind(this)
            this.list = this.list.bind(this)
            this.view = this.view.bind(this)
        }

        public async create(params: RequestType<typeof api_status_create_create>): Promise<ResponseType<typeof api_status_create_create>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/statuses`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_status_create_create>
        }

        public async getViewers(params: { statusId: string }): Promise<ResponseType<typeof api_status_get_viewers_getViewers>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/statuses/${encodeURIComponent(params.statusId)}/viewers`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_status_get_viewers_getViewers>
        }

        public async list(): Promise<ResponseType<typeof api_status_list_list>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/statuses`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_status_list_list>
        }

        public async view(params: { statusId: string }): Promise<ResponseType<typeof api_status_view_view>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/statuses/${encodeURIComponent(params.statusId)}/view`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_status_view_view>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { checkUsername as api_user_check_username_checkUsername } from "~backend/user/check_username";
import { completeProfileSetup as api_user_complete_profile_setup_completeProfileSetup } from "~backend/user/complete_profile_setup";
import { getCurrentUser as api_user_get_current_getCurrentUser } from "~backend/user/get_current";
import { getProfile as api_user_get_profile_getProfile } from "~backend/user/get_profile";
import { search as api_user_search_search } from "~backend/user/search";
import { updateProfile as api_user_update_profile_updateProfile } from "~backend/user/update_profile";
import { uploadAvatar as api_user_upload_avatar_uploadAvatar } from "~backend/user/upload_avatar";

export namespace user {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.checkUsername = this.checkUsername.bind(this)
            this.completeProfileSetup = this.completeProfileSetup.bind(this)
            this.getCurrentUser = this.getCurrentUser.bind(this)
            this.getProfile = this.getProfile.bind(this)
            this.search = this.search.bind(this)
            this.updateProfile = this.updateProfile.bind(this)
            this.uploadAvatar = this.uploadAvatar.bind(this)
        }

        public async checkUsername(params: RequestType<typeof api_user_check_username_checkUsername>): Promise<ResponseType<typeof api_user_check_username_checkUsername>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/check-username`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_check_username_checkUsername>
        }

        public async completeProfileSetup(params: RequestType<typeof api_user_complete_profile_setup_completeProfileSetup>): Promise<ResponseType<typeof api_user_complete_profile_setup_completeProfileSetup>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/complete-profile`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_complete_profile_setup_completeProfileSetup>
        }

        public async getCurrentUser(): Promise<ResponseType<typeof api_user_get_current_getCurrentUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/me`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_get_current_getCurrentUser>
        }

        public async getProfile(params: { userId: string }): Promise<ResponseType<typeof api_user_get_profile_getProfile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.userId)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_get_profile_getProfile>
        }

        public async search(params: RequestType<typeof api_user_search_search>): Promise<ResponseType<typeof api_user_search_search>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                query: params.query,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/search`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_search_search>
        }

        public async updateProfile(params: RequestType<typeof api_user_update_profile_updateProfile>): Promise<ResponseType<typeof api_user_update_profile_updateProfile>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/me`, {method: "PUT", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_update_profile_updateProfile>
        }

        public async uploadAvatar(): Promise<ResponseType<typeof api_user_upload_avatar_uploadAvatar>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/me/avatar/upload-url`, {method: "POST", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_upload_avatar_uploadAvatar>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | RequestType<typeof auth_auth>
  | Promise<RequestType<typeof auth_auth> | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.51.6)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: RequestType<typeof auth_auth> | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
